# Generated by Django 5.0.6 on 2024-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(help_text='write full name', max_length=35, verbose_name='full name')),
                ('image', models.ImageField(upload_to='blog/author/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
