# Generated by Django 5.0.6 on 2024-07-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='BlogPostModel',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
