# Generated by Django 5.0.6 on 2024-07-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='caption',
        ),
        migrations.DeleteModel(
            name='CaptionModel',
        ),
    ]
